server:
  port:  8081

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
#    <기존 오라클 사용 방식>
#    url: jdbc:oracle:thin@localhost:1521:XE
#    url: jdbc:oracle:thin:@oracle11g:1521:XE #localhost를 도커 컨테이너 명으로 해주어야 됨.
#    username: system
#    password: oracle

    url: "#####" #localhost를 AWS 명으로 해주어야 됨.
    username: sysdba
    password: oracleoracle!

mybatis:
  type-aliases-package: com.kcc.spring_docker.vo
  mapper-locations: classpath:mapper/*.xml
